/**
 * Execute-action use case: the enforcement boundary (spec §13, §24, §25, §64).
 *
 * Guarantee: the executor NEVER runs before the firewall reaches a decision
 * (invariant 1), and for policies keeping the default, state is re-fetched
 * immediately before the side effect to narrow the time-of-check/time-of-use
 * window (spec §13).
 *
 * Replay protection (spec §24): one action id gets exactly one authorization
 * and one execution attempt. Replaying an executed, expired, or live
 * authorization raises ReplayDetectedError / ActionExpiredError. Idempotent
 * executors may retry when the policy explicitly allows it (spec §25).
 */

import type { ActionExecutor, ActionIntent, ExecutionResult, Precondition } from '../domain/action.js';
import type { DecisionRecord } from '../domain/decision.js';
import type { AuthorizationRecord } from '../storage/types.js';
import { ActionExpiredError, ReplayDetectedError, EscalationPendingError, UnauthorizedActionError } from '../domain/errors.js';
import type { FirewallContext } from './context.js';
import {
  validateAction,
  buildDecisionRecord,
  fingerprintOf,
  collectPreconditions,
} from './validate-action.js';
import type { ActionIntentInput } from '../domain/action.js';
import { recomputeVerdictsFromCurrentState } from './revalidate-action.js';
import { evaluateDependencies, routePreconditions } from '../engine/dependency-evaluator.js';
import { decide } from '../engine/decision-engine.js';
import { resolveDependencyFreshness } from '../engine/policy-resolver.js';
import { defaultDeadlineForRisk } from '../engine/resolved-policy.js';
import { newId, ID_PREFIXES } from '../domain/identifiers.js';

export interface ExecutionOutcome {
  decision: DecisionRecord;
  /** Whether the side effect was performed. */
  executed: boolean;
  result: ExecutionResult | null;
  /** Present when the initial decision was REVALIDATE and was recomputed. */
  revalidatedDecision: DecisionRecord | null;
}

export interface ExecuteOptions {
  /** Reuse an existing action id (retry flows); new ids are generated by default. */
  actionId?: string;
  /** Internal: the call comes from the approved-escalation path. */
  viaApproval?: boolean;
}

export async function executeAction(
  ctx: FirewallContext,
  intentInput: ActionIntentInput,
  executor: ActionExecutor,
  options: ExecuteOptions = {},
): Promise<ExecutionOutcome> {
  // ---- Escalation state machine guards ------------------------------------
  if (options.actionId && !options.viaApproval) {
    const escalation = await ctx.store.getEscalation(options.actionId);
    if (escalation) {
      if (escalation.status === 'PENDING') {
        throw new EscalationPendingError(options.actionId);
      }
      if (escalation.status === 'APPROVED') {
        throw new UnauthorizedActionError(
          `action ${options.actionId} has an approved escalation; execute it via executeApproved()`,
        );
      }
      throw new ReplayDetectedError(options.actionId, { reason: 'escalation was rejected; the action cannot run' });
    }
  }

  const validation = await validateAction(ctx, intentInput, { actionId: options.actionId });
  const intent = validation.intent;
  const policy = validation.policy;

  // ---- Replay guard (spec §24) -------------------------------------------
  const existingAuth = await ctx.store.getAuthorization(intent.action_id);
  if (existingAuth && existingAuth.consumed_at === null && Date.parse(existingAuth.expires_at) < ctx.clock.nowMs()) {
    ctx.audit.append('action.expired', {
      action_id: intent.action_id,
      reason: `authorization expired at ${existingAuth.expires_at} before execution`,
    });
    throw new ActionExpiredError(intent.action_id, existingAuth.expires_at);
  }
  if (existingAuth) {
    if (existingAuth.consumed_at !== null) {
      if (policy.execution.allowIdempotentRetry && executor.idempotency === 'idempotent') {
        // Safe retry: a full fresh validation + execution happens below.
        ctx.audit.append('action.validated', {
          action_id: intent.action_id,
          note: 'idempotent retry permitted by policy; prior authorization consumed',
          execution_status: 'not_executed',
        });
      } else {
        ctx.metrics.increment('replays_detected');
        ctx.audit.append('action.replay_detected', {
          action_id: intent.action_id,
          agent_id: intent.agent_id,
          reason: 'authorization already consumed; action cannot be replayed',
        });
        throw new ReplayDetectedError(intent.action_id, {
          authorized_at: existingAuth.authorized_at,
          consumed_at: existingAuth.consumed_at,
        });
      }
    } else {
      ctx.metrics.increment('replays_detected');
      ctx.audit.append('action.replay_detected', {
        action_id: intent.action_id,
        agent_id: intent.agent_id,
        reason: 'a live authorization already exists for this action id',
      });
      throw new ReplayDetectedError(intent.action_id, { authorized_at: existingAuth.authorized_at });
    }
  }

  let decision = validation.decision;
  let revalidatedDecision: DecisionRecord | null = null;

  // ---- Revalidation flow (spec §23) --------------------------------------
  if (decision.decision === 'REVALIDATE') {
    const revalidationStart = ctx.clock.nowMs();
    const recomputedVerdicts = recomputeVerdictsFromCurrentState({
      originalVerdicts: decision.verdicts,
      fetched: validation.snapshots,
      routedPreconditions: routeAll(collectPreconditions(policy, intent), intent),
      resolveDependencyFreshness: (index) => {
        const dep = intent.dependencies[index];
        return dep ? resolveDependencyFreshness(policy, dep, policy.freshness) : policy.freshness;
      },
      nowMs: ctx.clock.nowMs(),
    });

    const output = decide({
      intent,
      policy,
      defaults: ctx.defaults,
      verdicts: recomputedVerdicts,
      mode: ctx.mode,
      revalidated: true,
    });

    const deadlineMs = policy.execution.deadlineMs ?? defaultDeadlineForRisk(intent.risk_level ?? 'MEDIUM');
    const record = buildDecisionRecord({
      ctx,
      intent,
      policy,
      decision: output.decision,
      reason: output.reason,
      verdicts: recomputedVerdicts,
      deadlineMs,
      revalidated: true,
      computedAt: ctx.clock.nowMs(),
    });
    if (ctx.mode === 'OBSERVE' && record.decision !== 'ALLOW') {
      record.would_have_decided = record.decision;
      record.decision = 'ALLOW';
      record.reason = `OBSERVE mode: decision recorded without blocking. ${record.reason}`;
    }
    await ctx.store.saveDecision(record);
    revalidatedDecision = record;
    decision = record;
    ctx.metrics.observeRevalidationLatency(ctx.clock.nowMs() - revalidationStart);
    ctx.audit.append('action.revalidated', {
      action_id: intent.action_id,
      decision: record.decision,
      reason: record.reason,
    });
  }

  // ---- ESCALATE: hold for human approval (spec §6) ------------------------
  if (decision.decision === 'ESCALATE') {
    if (options.viaApproval) {
      // Human approval resolves the uncertainty that caused the escalation;
      // every other safety property (INVALID, failed preconditions) still blocks.
      decision = {
        ...decision,
        decision: 'ALLOW',
        reason: `escalation approved; proceeding under fresh-state enforcement. ${decision.reason}`,
      };
    } else {
      await ctx.store.saveEscalation({
      action_id: intent.action_id,
      decision_id: decision.decision_id,
      status: 'PENDING',
      requested_at: ctx.clock.nowIso(),
      resolved_at: null,
      resolved_by: null,
      resolution_note: null,
    });
      ctx.metrics.increment('escalations_requested');
      ctx.audit.append('action.escalation_requested', {
        action_id: intent.action_id,
        decision: 'ESCALATE',
        reason: decision.reason,
      });
      return { decision, executed: false, result: null, revalidatedDecision };
    }
  }

  // ---- DENY / remaining REVALIDATE: nothing executes ----------------------
  if (decision.decision !== 'ALLOW') {
    ctx.audit.append('action.blocked', {
      action_id: intent.action_id,
      decision: decision.decision,
      reason: decision.reason,
      execution_status: 'blocked',
    });
    return { decision, executed: false, result: null, revalidatedDecision };
  }

  // ---- Authorization (spec §24) -------------------------------------------
  const deadlineMs = policy.execution.deadlineMs ?? defaultDeadlineForRisk(intent.risk_level ?? 'MEDIUM');
  const nowMs = ctx.clock.nowMs();
  const expiresAt = new Date(nowMs + deadlineMs).toISOString();
  const auth: AuthorizationRecord = {
    action_id: intent.action_id,
    decision_id: decision.decision_id,
    authorized_at: decision.created_at,
    expires_at: expiresAt,
    state_fingerprint: validation.stateFingerprint,
    consumed_at: null,
    policy_version: ctx.policyVersion,
  };
  await ctx.store.saveAuthorization(auth);

  // ---- TOCTOU re-verification immediately before the side effect ----------
  if (policy.execution.requireFreshAtExecution) {
    const recheck = await evaluateDependencies({
      dependencies: intent.dependencies,
      policyFreshness: policy.freshness,
      resolveDependencyFreshness: (dep) => resolveDependencyFreshness(policy, dep, policy.freshness),
      preconditions: collectPreconditions(policy, intent),
      providers: ctx.providers,
      nowMs: ctx.clock.nowMs(),
      nowIso: ctx.clock.nowIso(),
      events: ctx.events,
    });
    for (const snapshot of recheck.fetched) {
      await ctx.store.saveSnapshot(snapshot);
    }
    const currentFingerprint = fingerprintOf(recheck.fetched);
    if (recheck.fetched.length > 0 && currentFingerprint !== validation.stateFingerprint) {
      const blockedRecord = buildDecisionRecord({
        ctx,
        intent,
        policy,
        decision: 'DENY',
        reason:
          'state changed between validation and execution (time-of-check/time-of-use protection); ' +
          'authorized state fingerprint no longer matches current state',
        verdicts: recheck.verdicts,
        deadlineMs,
        revalidated: true,
        computedAt: ctx.clock.nowMs(),
      });
      await ctx.store.saveDecision(blockedRecord);
      ctx.audit.append('action.blocked', {
        action_id: intent.action_id,
        decision: 'DENY',
        reason: blockedRecord.reason,
        execution_status: 'blocked',
        stage: 'toctou_recheck',
      });
      return { decision: blockedRecord, executed: false, result: null, revalidatedDecision };
    }
  }

  // ---- Execute with deadline (spec §13) -----------------------------------
  const executionId = newId(ID_PREFIXES.execution, ctx.clock.nowMs());
  const startedAt = ctx.clock.nowIso();
  const startMs = ctx.clock.nowMs();

  let raw: Awaited<ReturnType<ActionExecutor['execute']>>;
  try {
    raw = await Promise.race([
      executor.execute(intent),
      deadlineRace(startMs + deadlineMs, intent.action_id, deadlineMs),
    ]);
  } catch (error) {
    const finishedAt = ctx.clock.nowIso();
    const failed: ExecutionResult = {
      execution_id: executionId,
      action_id: intent.action_id,
      success: false,
      idempotency: executor.idempotency,
      error: error instanceof Error ? error.message : String(error),
      started_at: startedAt,
      finished_at: finishedAt,
      duration_ms: ctx.clock.nowMs() - startMs,
      atomicity: executor.atomicity ?? 'not_guaranteed',
    };
    await ctx.store.saveExecution(failed);
    await ctx.store.consumeAuthorization(intent.action_id, finishedAt);
    ctx.audit.append('action.failed', {
      action_id: intent.action_id,
      execution_status: 'failed',
      reason: failed.error,
      latency_ms: failed.duration_ms,
      note: failed.error?.includes('deadline') === true
        ? 'the side effect may still have been performed by the executor; atomicity is not guaranteed'
        : undefined,
    });
    return { decision, executed: true, result: failed, revalidatedDecision };
  }

  const finishedAt = ctx.clock.nowIso();
  const result: ExecutionResult = {
    execution_id: executionId,
    action_id: intent.action_id,
    success: raw.success,
    idempotency: executor.idempotency,
    output: raw.output,
    error: raw.error,
    started_at: startedAt,
    finished_at: finishedAt,
    duration_ms: ctx.clock.nowMs() - startMs,
    atomicity: executor.atomicity ?? 'not_guaranteed',
  };

  // Authorization is consumed exactly once, together with the outcome.
  await ctx.store.consumeAuthorization(intent.action_id, finishedAt);
  await ctx.store.saveExecution(result);

  const persistedDecision: DecisionRecord = { ...decision, execution: result };

  ctx.metrics.observeExecutionLatency(result.duration_ms);
  ctx.audit.append(result.success ? 'action.executed' : 'action.failed', {
    action_id: intent.action_id,
    agent_id: intent.agent_id,
    tool: intent.tool,
    operation: intent.operation,
    target: intent.target,
    decision: decision.decision,
    execution_status: result.success ? 'executed' : 'failed',
    latency_ms: result.duration_ms,
    atomicity: result.atomicity,
    reason: result.success ? 'executed after fresh-state validation' : result.error ?? 'executor reported failure',
  });

  return { decision: persistedDecision, executed: true, result, revalidatedDecision };
}

/** Approved-execution path: escalation approved by a human, freshness re-verified. */
export async function executeApprovedAction(
  ctx: FirewallContext,
  actionId: string,
  intentInput: ActionIntentInput,
  executor: ActionExecutor,
): Promise<ExecutionOutcome> {
  const escalation = await ctx.store.getEscalation(actionId);
  if (!escalation) {
    throw new ReplayDetectedError(actionId, { reason: 'no escalation record exists for this action id' });
  }
  if (escalation.status !== 'APPROVED') {
    ctx.audit.append('action.blocked', {
      action_id: actionId,
      decision: 'ESCALATE',
      execution_status: 'blocked',
      reason: `escalation status is ${escalation.status}; approval is required`,
    });
    throw new ReplayDetectedError(actionId, { reason: `escalation status is ${escalation.status}` });
  }
  ctx.audit.append('action.validated', {
    action_id: actionId,
    note: `executing approved escalation (approved by ${escalation.resolved_by ?? 'unknown'}); freshness is re-verified`,
    execution_status: 'not_executed',
  });
  return executeAction(ctx, intentInput, executor, { actionId, viaApproval: true });
}

function routeAll(preconditions: Precondition[], intent: ActionIntent): Precondition[][] {
  return intent.dependencies.map((dep, index) => routePreconditions(preconditions, index, dep));
}

function deadlineRace(_deadlineAtMs: number, actionId: string, deadlineMs: number): Promise<never> {
  return new Promise((_resolve, reject) => {
    // The timer duration equals the configured deadline: the authorization
    // window starts when validation completes, regardless of clock domain.
    const timer = setTimeout(() => {
      reject(new Error(`action ${actionId} exceeded its ${deadlineMs}ms execution deadline`));
    }, Math.max(0, deadlineMs));
    if (typeof timer.unref === 'function') {
      timer.unref();
    }
  });
}
