/**
 * Execute-action use case: the enforcement boundary (spec §13, §24, §25, §64).
 *
 * Guarantee: the executor NEVER runs before the firewall reaches a decision
 * (invariant 1), and for policies keeping the default, state is re-fetched
 * immediately before the side effect to narrow the time-of-check/time-of-use
 * window (spec §13).
 *
 * Replay protection (spec §24): one action id gets exactly one authorization
 * and one execution attempt. Replaying an executed, expired, or live
 * authorization raises ReplayDetectedError / ActionExpiredError. Idempotent
 * executors may retry when the policy explicitly allows it (spec §25).
 */

import type {
  ActionExecutor,
  ActionIntent,
  ConditionalExecutionResult,
  ExecutionResult,
  ExpectedStateEntry,
  Precondition,
} from '../domain/action.js';
import type { DecisionRecord } from '../domain/decision.js';
import type { AuthorizationRecord } from '../storage/types.js';
import type { StateSnapshot } from '../domain/state.js';
import { ActionExpiredError, ReplayDetectedError, EscalationPendingError, UnauthorizedActionError } from '../domain/errors.js';
import type { FirewallContext } from './context.js';
import {
  validateAction,
  buildDecisionRecord,
  fingerprintOf,
  collectPreconditions,
} from './validate-action.js';
import type { ActionIntentInput } from '../domain/action.js';
import { normalizeIntent } from './normalize-intent.js';
import { recomputeVerdictsFromCurrentState } from './revalidate-action.js';
import { evaluateDependencies, routePreconditions } from '../engine/dependency-evaluator.js';
import { decide } from '../engine/decision-engine.js';
import { resolveDependencyFreshness } from '../engine/policy-resolver.js';
import { defaultDeadlineForRisk, type ResolvedPolicy } from '../engine/resolved-policy.js';
import { newId, ID_PREFIXES } from '../domain/identifiers.js';
import { refKey } from '../domain/state.js';
import { canonicalJson } from '../engine/hashing.js';
import { redactDeep } from '../redaction/redact.js';
import { guidanceFor } from '../domain/recovery.js';

export interface ExecutionOutcome {
  decision: DecisionRecord;
  /** Whether the side effect was performed. */
  executed: boolean;
  result: ExecutionResult | null;
  /** Present when the initial decision was REVALIDATE and was recomputed. */
  revalidatedDecision: DecisionRecord | null;
}

export interface ExecuteOptions {
  /** Reuse an existing action id (retry flows); new ids are generated by default. */
  actionId?: string;
  /** Internal: the call comes from the approved-escalation path. */
  viaApproval?: boolean;
}

export async function executeAction(
  ctx: FirewallContext,
  intentInput: ActionIntentInput,
  executor: ActionExecutor,
  options: ExecuteOptions = {},
): Promise<ExecutionOutcome> {
  // ---- Escalation state machine guards ------------------------------------
  // These run BEFORE validation: a replayed or held action id must not trigger
  // provider fetches, persist a new action row, or audit a proposal.
  if (options.actionId && !options.viaApproval) {
    const escalation = await ctx.store.getEscalation(options.actionId);
    if (escalation) {
      if (escalation.status === 'PENDING') {
        throw new EscalationPendingError(options.actionId);
      }
      if (escalation.status === 'APPROVED') {
        throw new UnauthorizedActionError(
          `action ${options.actionId} has an approved escalation; execute it via executeApproved()`,
        );
      }
      throw new ReplayDetectedError(options.actionId, { reason: 'escalation was rejected; the action cannot run' });
    }
  }

  // ---- Expiry + live-authorization replay guards (fail fast) --------------
  if (options.actionId) {
    const earlyAuth = await ctx.store.getAuthorization(options.actionId);
    if (earlyAuth && earlyAuth.consumed_at === null && Date.parse(earlyAuth.expires_at) < ctx.clock.nowMs()) {
      ctx.audit.append('action.expired', {
        action_id: options.actionId,
        reason: `authorization expired at ${earlyAuth.expires_at} before execution`,
      });
      throw new ActionExpiredError(options.actionId, earlyAuth.expires_at);
    }
    if (earlyAuth && earlyAuth.consumed_at === null) {
      ctx.metrics.increment('replays_detected');
      ctx.audit.append('action.replay_detected', {
        action_id: options.actionId,
        reason: 'a live authorization already exists for this action id',
      });
      throw new ReplayDetectedError(options.actionId, { authorized_at: earlyAuth.authorized_at });
    }
  }

  const validation = await validateAction(ctx, intentInput, { actionId: options.actionId });
  const intent = validation.intent;
  const policy = validation.policy;

  // ---- Consumed-authorization guard (spec §24) ----------------------------
  const existingAuth = await ctx.store.getAuthorization(intent.action_id);
  if (existingAuth && existingAuth.consumed_at !== null) {
    if (policy.execution.allowIdempotentRetry && executor.idempotency === 'idempotent') {
      // Safe retry: a full fresh validation + execution happens below.
      ctx.audit.append('action.validated', {
        action_id: intent.action_id,
        note: 'idempotent retry permitted by policy; prior authorization consumed',
        execution_status: 'not_executed',
      });
    } else {
      ctx.metrics.increment('replays_detected');
      ctx.audit.append('action.replay_detected', {
        action_id: intent.action_id,
        agent_id: intent.agent_id,
        reason: 'authorization already consumed; action cannot be replayed',
      });
      throw new ReplayDetectedError(intent.action_id, {
        authorized_at: existingAuth.authorized_at,
        consumed_at: existingAuth.consumed_at,
      });
    }
  }

  let decision = validation.decision;
  let revalidatedDecision: DecisionRecord | null = null;

  // ---- Revalidation flow (spec §23) --------------------------------------
  if (decision.decision === 'REVALIDATE') {
    const revalidationStart = ctx.clock.nowMs();
    const recomputedVerdicts = recomputeVerdictsFromCurrentState({
      originalVerdicts: decision.verdicts,
      fetched: validation.snapshots,
      routedPreconditions: routeAll(collectPreconditions(policy, intent), intent),
      resolveDependencyFreshness: (index) => {
        const dep = intent.dependencies[index];
        return dep ? resolveDependencyFreshness(policy, dep, policy.freshness) : policy.freshness;
      },
      nowMs: ctx.clock.nowMs(),
    });

    const output = decide({
      intent,
      policy,
      defaults: ctx.defaults,
      verdicts: recomputedVerdicts,
      mode: ctx.mode,
      revalidated: true,
    });

    const deadlineMs = policy.execution.deadlineMs ?? defaultDeadlineForRisk(intent.risk_level ?? 'MEDIUM');
    const record = buildDecisionRecord({
      ctx,
      intent,
      policy,
      decision: output.decision,
      reason: output.reason,
      verdicts: recomputedVerdicts,
      deadlineMs,
      revalidated: true,
      computedAt: ctx.clock.nowMs(),
    });
    if (ctx.mode === 'OBSERVE' && record.decision !== 'ALLOW') {
      record.would_have_decided = record.decision;
      record.decision = 'ALLOW';
      record.reason = `OBSERVE mode: decision recorded without blocking. ${record.reason}`;
    }
    await ctx.store.saveDecision(record);
    revalidatedDecision = record;
    decision = record;
    ctx.metrics.observeRevalidationLatency(ctx.clock.nowMs() - revalidationStart);
    ctx.audit.append('action.revalidated', {
      action_id: intent.action_id,
      decision: record.decision,
      reason: record.reason,
    });
  }

  // ---- ESCALATE: hold for human approval (spec §6) ------------------------
  if (decision.decision === 'ESCALATE') {
    if (options.viaApproval) {
      // Human approval resolves the uncertainty that caused the escalation;
      // every other safety property (INVALID, failed preconditions) still blocks.
      decision = {
        ...decision,
        decision: 'ALLOW',
        reason: `escalation approved; proceeding under fresh-state enforcement. ${decision.reason}`,
      };
    } else {
      await ctx.store.saveEscalation({
      action_id: intent.action_id,
      decision_id: decision.decision_id,
      status: 'PENDING',
      requested_at: ctx.clock.nowIso(),
      resolved_at: null,
      resolved_by: null,
      resolution_note: null,
    });
      ctx.metrics.increment('escalations_requested');
      ctx.audit.append('action.escalation_requested', {
        action_id: intent.action_id,
        decision: 'ESCALATE',
        reason: decision.reason,
      });
      return { decision, executed: false, result: null, revalidatedDecision };
    }
  }

  // ---- DENY / remaining REVALIDATE: nothing executes ----------------------
  if (decision.decision !== 'ALLOW') {
    ctx.audit.append('action.blocked', {
      action_id: intent.action_id,
      decision: decision.decision,
      reason: decision.reason,
      execution_status: 'blocked',
    });
    return { decision, executed: false, result: null, revalidatedDecision };
  }

  // ---- Authorization (spec §24) -------------------------------------------
  // The claim is atomic: if a live (unconsumed) authorization already exists
  // for this action id, the claim is refused. This closes the check-then-insert
  // window that two concurrent executions could otherwise both pass.
  //
  // The authorization binds the action to the EXACT state identity it was
  // granted against (milestone: atomic effect assurance): one expected-state
  // entry per validated dependency. Conditional executors forward these
  // entries to the external system so THAT system rejects the operation when
  // the authorized state is no longer true.
  const expectedState = buildExpectedState(validation.snapshots);
  const executorConditional =
    typeof executor.conditionalExecutionSupported === 'function' &&
    executor.conditionalExecutionSupported() === true &&
    typeof executor.conditionalExecute === 'function';
  const conditionalExecutionAvailable = executorConditional && expectedState.length > 0;

  // ---- Policy gate: conditional execution required but unenforceable ------
  // A policy that demands provider-enforced conditional execution must not
  // silently fall back to best-effort pre-execution verification. A human
  // approval cannot give a provider compare-and-swap semantics, so the
  // default outcome is DENY (fail closed), not ESCALATE. In OBSERVE mode the
  // gate outcome is recorded without blocking; approved escalations
  // (viaApproval) proceed under the documented best-effort guarantee.
  if (
    policy.execution.requireConditionalExecution === true &&
    !conditionalExecutionAvailable &&
    options.viaApproval !== true
  ) {
    const outcomeDecision = policy.execution.onConditionalUnavailable ?? 'deny';
    const gateDecision =
      outcomeDecision === 'revalidate' ? 'REVALIDATE' : outcomeDecision === 'escalate' ? 'ESCALATE' : 'DENY';
    const deadlineMsUnavailable = policy.execution.deadlineMs ?? defaultDeadlineForRisk(intent.risk_level ?? 'MEDIUM');
    const blockedRecord = buildDecisionRecord({
      ctx,
      intent,
      policy,
      decision: gateDecision,
      reason:
        `policy "${policy.name}" requires provider-side conditional execution, but the executor cannot enforce ` +
        `the authorized expected state at the external system for this action (provider capability: ` +
        `${conditionalCapabilityOf(ctx.providers, intent)}); failing closed with outcome ${gateDecision}`,
      verdicts: validation.decision.verdicts,
      deadlineMs: deadlineMsUnavailable,
      revalidated: false,
      computedAt: ctx.clock.nowMs(),
    });
    if (ctx.mode === 'OBSERVE') {
      // OBSERVE mode never blocks: record the gate outcome and proceed.
      blockedRecord.would_have_decided = blockedRecord.decision;
      blockedRecord.decision = 'ALLOW';
      blockedRecord.reason = `OBSERVE mode: decision recorded without blocking. ${blockedRecord.reason}`;
      await ctx.store.saveDecision(blockedRecord);
      ctx.audit.append('action.blocked', {
        action_id: intent.action_id,
        decision: 'ALLOW',
        would_have: blockedRecord.would_have_decided,
        reason: blockedRecord.reason,
        execution_status: 'not_executed',
        stage: 'conditional_execution_unavailable',
        note: 'OBSERVE mode: the conditional-execution gate outcome is recorded without blocking',
      });
    } else if (gateDecision === 'ESCALATE') {
      // The escalation references this decision record; it must be persisted.
      await ctx.store.saveDecision(blockedRecord);
      await ctx.store.saveEscalation({
        action_id: intent.action_id,
        decision_id: blockedRecord.decision_id,
        status: 'PENDING',
        requested_at: ctx.clock.nowIso(),
        resolved_at: null,
        resolved_by: null,
        resolution_note: null,
      });
      ctx.metrics.increment('escalations_requested');
      ctx.audit.append('action.escalation_requested', {
        action_id: intent.action_id,
        decision: 'ESCALATE',
        reason: blockedRecord.reason,
      });
      return { decision: blockedRecord, executed: false, result: null, revalidatedDecision };
    } else {
      await ctx.store.saveDecision(blockedRecord);
      ctx.audit.append('action.blocked', {
        action_id: intent.action_id,
        decision: gateDecision,
        reason: blockedRecord.reason,
        execution_status: 'blocked',
        stage: 'conditional_execution_unavailable',
      });
      return { decision: blockedRecord, executed: false, result: null, revalidatedDecision };
    }
  }

  const deadlineMs = policy.execution.deadlineMs ?? defaultDeadlineForRisk(intent.risk_level ?? 'MEDIUM');
  const nowMs = ctx.clock.nowMs();
  const expiresAt = new Date(nowMs + deadlineMs).toISOString();
  const auth: AuthorizationRecord = {
    action_id: intent.action_id,
    decision_id: decision.decision_id,
    authorized_at: decision.created_at,
    expires_at: expiresAt,
    state_fingerprint: validation.stateFingerprint,
    expected_state: conditionalExecutionAvailable ? expectedState : null,
    consumed_at: null,
    policy_version: ctx.policyVersion,
  };
  const claim = await ctx.store.claimAuthorization(auth);
  if (!claim.claimed) {
    ctx.metrics.increment('replays_detected');
    ctx.audit.append('action.replay_detected', {
      action_id: intent.action_id,
      agent_id: intent.agent_id,
      reason: 'a live authorization already exists for this action id',
    });
    throw new ReplayDetectedError(intent.action_id, {
      authorized_at: claim.existing?.authorized_at ?? null,
    });
  }

  // ---- Provider-enforced conditional execution -----------------------------
  // When the executor can enforce the authorized expected state at the
  // external system, the condition is checked ATOMICALLY BY THE PROVIDER at
  // the moment of mutation. This REPLACES the fetch-compare re-check below:
  // a pre-execution read cannot close the compare -> execute window, while a
  // provider-side compare-and-swap eliminates it (milestone §28: no
  // redundant verification where provider semantics make it safe).
  if (conditionalExecutionAvailable) {
    return executeConditionally(ctx, {
      intent,
      executor,
      policy,
      decision,
      revalidatedDecision,
      expectedState,
      deadlineMs,
    });
  }

  // ---- TOCTOU re-verification immediately before the side effect ----------
  if (policy.execution.requireFreshAtExecution) {
    const recheck = await evaluateDependencies({
      dependencies: intent.dependencies,
      policyFreshness: policy.freshness,
      resolveDependencyFreshness: (dep) => resolveDependencyFreshness(policy, dep, policy.freshness),
      preconditions: collectPreconditions(policy, intent),
      providers: ctx.providers,
      nowMs: ctx.clock.nowMs(),
      nowIso: ctx.clock.nowIso(),
      events: ctx.events,
    });
    for (const snapshot of recheck.fetched) {
      await ctx.store.saveSnapshot(snapshot);
    }
    if (intent.dependencies.length > 0 && recheck.fetched.length === 0) {
      // Every provider fetch failed during re-verification: the authorized
      // fingerprint can no longer be compared against the world, so the
      // safety basis of this execution is gone -> fail closed (invariant 7).
      const blockedRecord = buildDecisionRecord({
        ctx,
        intent,
        policy,
        decision: 'DENY',
        reason:
          'pre-execution state re-verification could not be completed: every provider fetch failed; ' +
          'failing closed (time-of-check/time-of-use protection)',
        verdicts: recheck.verdicts,
        deadlineMs,
        revalidated: true,
        computedAt: ctx.clock.nowMs(),
      });
      await ctx.store.saveDecision(blockedRecord);
      ctx.audit.append('action.blocked', {
        action_id: intent.action_id,
        decision: 'DENY',
        reason: blockedRecord.reason,
        execution_status: 'blocked',
        stage: 'toctou_recheck',
      });
      return { decision: blockedRecord, executed: false, result: null, revalidatedDecision };
    }
    const currentFingerprint = fingerprintOf(recheck.fetched);
    if (recheck.fetched.length > 0 && currentFingerprint !== validation.stateFingerprint) {
      const blockedRecord = buildDecisionRecord({
        ctx,
        intent,
        policy,
        decision: 'DENY',
        reason:
          'state changed between validation and execution (time-of-check/time-of-use protection); ' +
          'authorized state fingerprint no longer matches current state',
        verdicts: recheck.verdicts,
        deadlineMs,
        revalidated: true,
        computedAt: ctx.clock.nowMs(),
      });
      await ctx.store.saveDecision(blockedRecord);
      ctx.audit.append('action.blocked', {
        action_id: intent.action_id,
        decision: 'DENY',
        reason: blockedRecord.reason,
        execution_status: 'blocked',
        stage: 'toctou_recheck',
      });
      return { decision: blockedRecord, executed: false, result: null, revalidatedDecision };
    }
  }

  // ---- Execute with deadline (spec §13) -----------------------------------
  const executionId = newId(ID_PREFIXES.execution, ctx.clock.nowMs());
  const startedAt = ctx.clock.nowIso();
  const startMs = ctx.clock.nowMs();

  let raw: Awaited<ReturnType<ActionExecutor['execute']>>;
  try {
    raw = await Promise.race([
      executor.execute(intent),
      deadlineRace(startMs + deadlineMs, intent.action_id, deadlineMs),
    ]);
  } catch (error) {
    const finishedAt = ctx.clock.nowIso();
    const deadlineBlown = error instanceof Error && error.message.includes('deadline') === true;
    // A deadline breach means the executor may still be running and may still
    // apply the effect: the outcome of the side effect is UNKNOWN. Any other
    // executor error is a clean reported failure (executor trust boundary).
    const recovery = deadlineBlown ? guidanceFor('unknown_execution_outcome') : guidanceFor('provider_failure');
    const failed: ExecutionResult = {
      execution_id: executionId,
      action_id: intent.action_id,
      success: false,
      idempotency: executor.idempotency,
      error: error instanceof Error ? error.message : String(error),
      started_at: startedAt,
      finished_at: finishedAt,
      duration_ms: ctx.clock.nowMs() - startMs,
      atomicity: executor.atomicity ?? 'not_guaranteed',
      conditional_execution: 'not_attempted',
      recovery,
    };
    await ctx.store.saveExecution(failed);
    await ctx.store.consumeAuthorization(intent.action_id, finishedAt);
    if (deadlineBlown) {
      ctx.metrics.increment('executions_unknown_outcome');
    }
    ctx.audit.append('action.failed', {
      action_id: intent.action_id,
      execution_status: 'failed',
      conditional_execution: 'not_attempted',
      reason: failed.error,
      latency_ms: failed.duration_ms,
      failure_kind: recovery.failure_kind,
      retry_safety: recovery.retry_safety,
      note: deadlineBlown
        ? 'the side effect may still have been performed by the executor; atomicity is not guaranteed'
        : undefined,
    });
    return { decision, executed: true, result: failed, revalidatedDecision };
  }

  const finishedAt = ctx.clock.nowIso();
  const result: ExecutionResult = {
    execution_id: executionId,
    action_id: intent.action_id,
    success: raw.success,
    idempotency: executor.idempotency,
    output: raw.output,
    error: raw.error,
    started_at: startedAt,
    finished_at: finishedAt,
    duration_ms: ctx.clock.nowMs() - startMs,
    atomicity: executor.atomicity ?? 'not_guaranteed',
    conditional_execution: 'not_attempted',
    // The trusted executor reported a clean failure: no side effect, but the
    // authorization is consumed and the next attempt re-decides from fresh state.
    ...(raw.success === false ? { recovery: guidanceFor('provider_failure') } : {}),
  };

  // Authorization is consumed exactly once, together with the outcome.
  // The persisted execution record carries redacted output; the live result
  // returned to the caller is the executor's own.
  await ctx.store.consumeAuthorization(intent.action_id, finishedAt);
  const persistedResult: ExecutionResult = { ...result, output: redactDeep(result.output) };
  await ctx.store.saveExecution(persistedResult);

  const persistedDecision: DecisionRecord = { ...decision, execution: persistedResult };

  ctx.metrics.observeExecutionLatency(result.duration_ms);
  ctx.audit.append(result.success ? 'action.executed' : 'action.failed', {
    action_id: intent.action_id,
    agent_id: intent.agent_id,
    tool: intent.tool,
    operation: intent.operation,
    target: intent.target,
    decision: decision.decision,
    execution_status: result.success ? 'executed' : 'failed',
    latency_ms: result.duration_ms,
    atomicity: result.atomicity,
    conditional_execution: 'not_attempted',
    reason: result.success ? 'executed after fresh-state validation' : result.error ?? 'executor reported failure',
  });

  return { decision: persistedDecision, executed: true, result, revalidatedDecision };
}

/** Approved-execution path: escalation approved by a human, freshness re-verified. */
export async function executeApprovedAction(
  ctx: FirewallContext,
  actionId: string,
  intentInput: ActionIntentInput,
  executor: ActionExecutor,
): Promise<ExecutionOutcome> {
  const escalation = await ctx.store.getEscalation(actionId);
  if (!escalation) {
    throw new ReplayDetectedError(actionId, { reason: 'no escalation record exists for this action id' });
  }
  if (escalation.status !== 'APPROVED') {
    ctx.audit.append('action.blocked', {
      action_id: actionId,
      decision: 'ESCALATE',
      execution_status: 'blocked',
      reason: `escalation status is ${escalation.status}; approval is required`,
    });
    throw new ReplayDetectedError(actionId, { reason: `escalation status is ${escalation.status}` });
  }

  // ---- Approval binding (authorization binds to approved semantics) -------
  // The human approved a specific action, not an action id that can later be
  // re-pointed at a different target, operation, or dependency set. The
  // submitted intent must match the semantics of the decision that was
  // escalated; otherwise the approval cannot be reused to execute it.
  const originalDecision = await ctx.store.getDecision(escalation.decision_id);
  if (!originalDecision) {
    throw new UnauthorizedActionError(
      `escalation for action ${actionId} references missing decision ${escalation.decision_id}`,
    );
  }
  const submitted = normalizeIntent(intentInput, ctx.clock.nowMs());

  // ---- Argument binding (dogfood finding DF-3) -----------------------------
  // A human approved a specific ACTION, arguments included. Resubmitting the
  // approved action id with different arguments must not inherit the
  // approval: compare the canonicalized REDACTED arguments of the persisted
  // action against the submitted ones. Redaction keeps the comparison honest
  // without persisting secrets in the error path.
  const originalAction = await ctx.store.getAction(actionId);
  const sameArguments =
    canonicalJson(redactDeep(originalAction?.arguments ?? {})) ===
    canonicalJson(redactDeep(submitted.arguments ?? {}));

  const originalDeps = originalDecision.verdicts.map((v) => refKey(v.dependency)).sort();
  const submittedDeps = submitted.dependencies.map((d) => refKey(d)).sort();
  const sameSemantics =
    originalDecision.tool === submitted.tool &&
    originalDecision.operation === submitted.operation &&
    (originalDecision.target ?? null) === (submitted.target ?? null) &&
    originalDeps.length === submittedDeps.length &&
    originalDeps.every((key, index) => key === submittedDeps[index]) &&
    sameArguments;
  if (!sameSemantics) {
    ctx.audit.append('action.blocked', {
      action_id: actionId,
      decision: 'ESCALATE',
      execution_status: 'blocked',
      reason:
        'escalation approval does not match the submitted action semantics; ' +
        'an approval binds to the originally approved operation, target, dependencies, and arguments',
    });
    throw new UnauthorizedActionError(
      `submitted action does not match the approved escalation for ${actionId}: ` +
        `approval binds to operation "${originalDecision.operation}", target "${originalDecision.target ?? 'none'}", ` +
        `dependencies [${originalDeps.join(', ')}]` +
        (sameArguments ? '' : ', and the originally approved arguments'),
    );
  }

  ctx.audit.append('action.validated', {
    action_id: actionId,
    note: `executing approved escalation (approved by ${escalation.resolved_by ?? 'unknown'}); freshness is re-verified`,
    execution_status: 'not_executed',
  });
  return executeAction(ctx, intentInput, executor, { actionId, viaApproval: true });
}

function routeAll(preconditions: Precondition[], intent: ActionIntent): Precondition[][] {
  return intent.dependencies.map((dep, index) => routePreconditions(preconditions, index, dep));
}

/** The per-dependency authorized state identity captured at validation time. */
function buildExpectedState(snapshots: readonly StateSnapshot[]): ExpectedStateEntry[] {
  return snapshots.map((s) => ({
    ref: refKey(s),
    version: s.version,
    content_hash: s.content_hash,
  }));
}

/** Human-auditable summary of the conditional-execution capability of the providers behind an intent. */
function conditionalCapabilityOf(providers: FirewallContext['providers'], intent: ActionIntent): string {
  const capabilities = intent.dependencies.map((dep) => {
    const provider = providers.find((p) => p.supports(dep));
    if (!provider) return `${refKey(dep)}: no provider`;
    if (provider.supportsConditionalExecution?.() === true) return `${refKey(dep)}: conditional_supported`;
    if (provider.supportsConditionalVerification?.() === true) return `${refKey(dep)}: best_effort_verification_only`;
    return `${refKey(dep)}: unsupported`;
  });
  return capabilities.join(', ') || 'no dependencies declared';
}

interface ConditionalExecutionParams {
  intent: ActionIntent;
  executor: ActionExecutor;
  policy: ResolvedPolicy;
  decision: DecisionRecord;
  revalidatedDecision: DecisionRecord | null;
  expectedState: ExpectedStateEntry[];
  deadlineMs: number;
}

/**
 * Executes the action through the executor's conditional path: the external
 * system itself enforces "only execute if state == authorized state".
 *
 * Outcome mapping (milestone §9, §10, §22):
 * - condition satisfied -> executed under a provider-enforced condition;
 *   atomicity is recorded as guaranteed.
 * - condition failed -> the provider REFUSED the stale operation. The
 *   authorization is invalidated; a completely fresh decision is computed
 *   from current state and recorded. The old authorization is never
 *   inherited and the operation is never blindly retried.
 * - condition unavailable -> the executor could not enforce the expected
 *   state for its effect: fail closed, nothing executes.
 * - provider crash/timeout -> execution failure with UNKNOWN condition
 *   outcome; never recorded as success.
 */
async function executeConditionally(
  ctx: FirewallContext,
  params: ConditionalExecutionParams,
): Promise<ExecutionOutcome> {
  const { intent, executor, policy, decision, revalidatedDecision, expectedState, deadlineMs } = params;
  const executionId = newId(ID_PREFIXES.execution, ctx.clock.nowMs());
  const startedAt = ctx.clock.nowIso();
  const startMs = ctx.clock.nowMs();
  const expectedStateForAudit = expectedState.map(({ ref, version }) => ({ ref, version }));
  // Per-dependency provider capability summary: makes the audit trail state
  // exactly which providers COULD enforce a condition behind this action.
  const providerCapability = conditionalCapabilityOf(ctx.providers, intent);

  let conditional: ConditionalExecutionResult;
  try {
    conditional = await Promise.race([
      executor.conditionalExecute!(intent, expectedState),
      deadlineRace(startMs + deadlineMs, intent.action_id, deadlineMs),
    ]);
  } catch (error) {
    // The conditional operation did not complete: the condition outcome is
    // UNKNOWN (the side effect may or may not have been applied). Record a
    // failure — never success — and consume the authorization. The record
    // states 'unknown' explicitly (operationalization milestone §11): the
    // caller must be able to see that the outcome was not observable.
    const finishedAt = ctx.clock.nowIso();
    const recovery = guidanceFor('unknown_execution_outcome');
    const failed: ExecutionResult = {
      execution_id: executionId,
      action_id: intent.action_id,
      success: false,
      idempotency: executor.idempotency,
      error: error instanceof Error ? error.message : String(error),
      started_at: startedAt,
      finished_at: finishedAt,
      duration_ms: ctx.clock.nowMs() - startMs,
      atomicity: executor.atomicity ?? 'not_guaranteed',
      conditional_execution: 'unknown',
      expected_state: expectedStateForAudit,
      recovery,
    };
    await ctx.store.saveExecution(failed);
    await ctx.store.consumeAuthorization(intent.action_id, finishedAt);
    ctx.metrics.increment('executions_unknown_outcome');
    ctx.audit.append('action.failed', {
      action_id: intent.action_id,
      agent_id: intent.agent_id,
      tool: intent.tool,
      operation: intent.operation,
      target: intent.target,
      decision: decision.decision,
      execution_status: 'failed',
      reason: failed.error,
      latency_ms: failed.duration_ms,
      atomicity: failed.atomicity,
      conditional_execution: 'unknown',
      expected_state: expectedStateForAudit,
      provider_capability: providerCapability,
      decision_ref: decision.decision_id,
      failure_kind: recovery.failure_kind,
      retry_safety: recovery.retry_safety,
      note: failed.error?.includes('deadline') === true
        ? 'the side effect may still have been performed by the executor; atomicity is not guaranteed'
        : 'the conditional operation did not complete; whether the provider evaluated the condition is unknown',
    });
    return { decision, executed: true, result: failed, revalidatedDecision };
  }

  // ---- CONDITION_FAILED: the external world moved after authorization ------
  // The provider correctly refused to execute the stale operation. This is
  // not an internal error and not a retryable failure: the authorization is
  // invalidated and a NEW decision is computed from CURRENT state. The new
  // state never inherits the old authorization (milestone §10).
  if (conditional.condition === 'failed') {
    const finishedAt = ctx.clock.nowIso();
    const rejected: ExecutionResult = {
      execution_id: executionId,
      action_id: intent.action_id,
      success: false,
      idempotency: executor.idempotency,
      error:
        conditional.error ??
        'conditional execution rejected by the provider: authoritative state no longer matches the authorized expected state',
      started_at: startedAt,
      finished_at: finishedAt,
      duration_ms: ctx.clock.nowMs() - startMs,
      // The condition was provider-enforced; the provider held the line.
      atomicity: 'guaranteed',
      conditional_execution: 'failed',
      expected_state: expectedStateForAudit,
      observed_version: conditional.observed_version,
      recovery: guidanceFor('condition_failed'),
    };
    await ctx.store.saveExecution(rejected);
    await ctx.store.consumeAuthorization(intent.action_id, finishedAt);
    ctx.metrics.increment('conditional_executions_failed');
    ctx.audit.append('execution.condition_failed', {
      action_id: intent.action_id,
      agent_id: intent.agent_id,
      tool: intent.tool,
      operation: intent.operation,
      target: intent.target,
      decision: decision.decision,
      execution_status: 'failed',
      conditional_execution: 'failed',
      expected_state: expectedStateForAudit,
      observed_version: conditional.observed_version,
      // DF-4 (dogfood): name the dependency whose expected state did not
      // hold and carry the executor's own refusal message, so a human reading
      // the audit can attribute a multi-dependency condition failure to a
      // specific ref without reading source code.
      failed_ref: conditional.ref ?? null,
      provider_error: conditional.error,
      provider: executorProviderName(ctx, intent) ?? undefined,
      provider_capability: providerCapability,
      decision_ref: decision.decision_id,
      failure_kind: 'condition_failed',
      retry_safety: 'SAFE_ONLY_AFTER_FRESH_EVALUATION',
      reason: 'provider refused the operation: the authorized state changed between authorization and execution',
    });

    // Recompute dependencies, preconditions, and policy against CURRENT
    // state, producing a NEW decision for the audit trail and for the
    // caller's next step. Nothing executes here regardless of the outcome.
    const fresh = await evaluateDependencies({
      dependencies: intent.dependencies,
      policyFreshness: policy.freshness,
      resolveDependencyFreshness: (dep) => resolveDependencyFreshness(policy, dep, policy.freshness),
      preconditions: collectPreconditions(policy, intent),
      providers: ctx.providers,
      nowMs: ctx.clock.nowMs(),
      nowIso: ctx.clock.nowIso(),
      events: ctx.events,
    });
    for (const snapshot of fresh.fetched) {
      await ctx.store.saveSnapshot(snapshot);
    }
    const recomputedVerdicts = recomputeVerdictsFromCurrentState({
      originalVerdicts: decision.verdicts,
      fetched: fresh.fetched,
      routedPreconditions: routeAll(collectPreconditions(policy, intent), intent),
      resolveDependencyFreshness: (index) => {
        const dep = intent.dependencies[index];
        return dep ? resolveDependencyFreshness(policy, dep, policy.freshness) : policy.freshness;
      },
      nowMs: ctx.clock.nowMs(),
    });
    const output = decide({
      intent,
      policy,
      defaults: ctx.defaults,
      verdicts: recomputedVerdicts,
      mode: ctx.mode,
      revalidated: true,
    });
    const freshDecision = buildDecisionRecord({
      ctx,
      intent,
      policy,
      decision: output.decision,
      reason:
        'conditional execution was rejected by the provider (authorized state changed between authorization and execution); ' +
        `the authorization was invalidated and a fresh decision was computed from current state. ${output.reason}`,
      verdicts: recomputedVerdicts,
      deadlineMs,
      revalidated: true,
      computedAt: ctx.clock.nowMs(),
      execution: redactExecutionForRecord(rejected),
    });
    if (ctx.mode === 'OBSERVE' && freshDecision.decision !== 'ALLOW') {
      freshDecision.would_have_decided = freshDecision.decision;
      freshDecision.decision = 'ALLOW';
      freshDecision.reason = `OBSERVE mode: decision recorded without blocking. ${freshDecision.reason}`;
    }
    await ctx.store.saveDecision(freshDecision);
    ctx.audit.append('action.blocked', {
      action_id: intent.action_id,
      decision: freshDecision.decision,
      reason: freshDecision.reason,
      execution_status: 'blocked',
      stage: 'condition_failed_revalidation',
      conditional_execution: 'failed',
      expected_state: expectedStateForAudit,
      observed_version: conditional.observed_version,
      decision_ref: decision.decision_id,
    });
    return { decision: freshDecision, executed: false, result: rejected, revalidatedDecision };
  }

  // ---- UNAVAILABLE: the executor could not enforce the condition -----------
  // Failing closed is the only safe outcome: the TOCTOU re-check was
  // replaced by the (now absent) provider-enforced condition, so a fallback
  // to unconditional execution would run with NO verification at all.
  if (conditional.condition === 'unavailable') {
    const finishedAt = ctx.clock.nowIso();
    const refused: ExecutionResult = {
      execution_id: executionId,
      action_id: intent.action_id,
      success: false,
      idempotency: executor.idempotency,
      error:
        conditional.error ??
        'conditional execution refused: the executor could not enforce the authorized expected state for this action',
      started_at: startedAt,
      finished_at: finishedAt,
      duration_ms: ctx.clock.nowMs() - startMs,
      atomicity: 'not_guaranteed',
      conditional_execution: 'unavailable',
      expected_state: expectedStateForAudit,
      recovery: guidanceFor('provider_failure'),
    };
    await ctx.store.saveExecution(refused);
    await ctx.store.consumeAuthorization(intent.action_id, finishedAt);
    ctx.audit.append('action.blocked', {
      action_id: intent.action_id,
      agent_id: intent.agent_id,
      tool: intent.tool,
      operation: intent.operation,
      target: intent.target,
      decision: decision.decision,
      execution_status: 'blocked',
      stage: 'conditional_execution_unavailable',
      conditional_execution: 'unavailable',
      expected_state: expectedStateForAudit,
      provider_capability: providerCapability,
      decision_ref: decision.decision_id,
      reason: 'executor could not enforce the authorized expected state; failing closed without executing',
    });
    return { decision, executed: false, result: refused, revalidatedDecision };
  }

  // ---- SATISFIED: the provider enforced the condition and it held ----------
  const finishedAt = ctx.clock.nowIso();
  const result: ExecutionResult = {
    execution_id: executionId,
    action_id: intent.action_id,
    success: conditional.success,
    idempotency: executor.idempotency,
    output: conditional.output,
    error: conditional.error,
    started_at: startedAt,
    finished_at: finishedAt,
    duration_ms: ctx.clock.nowMs() - startMs,
    atomicity: 'guaranteed',
    conditional_execution: 'satisfied',
    expected_state: expectedStateForAudit,
    // The condition held at the provider, but the operation itself can still
    // fail at the application level (trusted executor's word): clean failure,
    // no side effect, next attempt re-decides from fresh state.
    ...(conditional.success === false ? { recovery: guidanceFor('provider_failure') } : {}),
  };

  // Authorization is consumed exactly once, together with the outcome.
  // The persisted execution record carries redacted output; the live result
  // returned to the caller is the executor's own.
  await ctx.store.consumeAuthorization(intent.action_id, finishedAt);
  const persistedResult: ExecutionResult = { ...result, output: redactDeep(result.output) };
  await ctx.store.saveExecution(persistedResult);

  const persistedDecision: DecisionRecord = { ...decision, execution: persistedResult };

  ctx.metrics.increment('conditional_executions_satisfied');
  ctx.metrics.observeExecutionLatency(result.duration_ms);
  ctx.audit.append(result.success ? 'action.executed' : 'action.failed', {
    action_id: intent.action_id,
    agent_id: intent.agent_id,
    tool: intent.tool,
    operation: intent.operation,
    target: intent.target,
    decision: decision.decision,
    execution_status: result.success ? 'executed' : 'failed',
    latency_ms: result.duration_ms,
    atomicity: result.atomicity,
    conditional_execution: 'satisfied',
    expected_state: expectedStateForAudit,
    provider_capability: providerCapability,
    decision_ref: decision.decision_id,
    reason: result.success
      ? 'executed under provider-enforced conditional execution: the external system verified the authorized state at the moment of mutation'
      : conditional.error ?? 'executor reported failure after the condition was satisfied',
  });

  return { decision: persistedDecision, executed: true, result, revalidatedDecision };
}

function redactExecutionForRecord(result: ExecutionResult): ExecutionResult {
  return { ...result, output: redactDeep(result.output) };
}

function executorProviderName(ctx: FirewallContext, intent: ActionIntent): string | null {
  const dep = intent.dependencies[0];
  if (!dep) return null;
  return ctx.providers.find((p) => p.supports(dep))?.name ?? null;
}

function deadlineRace(_deadlineAtMs: number, actionId: string, deadlineMs: number): Promise<never> {
  return new Promise((_resolve, reject) => {
    // The timer duration equals the configured deadline: the authorization
    // window starts when validation completes, regardless of clock domain.
    const timer = setTimeout(() => {
      reject(new Error(`action ${actionId} exceeded its ${deadlineMs}ms execution deadline`));
    }, Math.max(0, deadlineMs));
    if (typeof timer.unref === 'function') {
      timer.unref();
    }
  });
}
